CREATE TABLE [tmp].[srv_resultados$] (
  [ID] [varchar](50) NULL,
  [Nombre] [varchar](100) NULL,
  [Razón social] [varchar](100) NULL,
  [NombreTienda] [varchar](50) NULL,
  [CodigoMall] [varchar](50) NULL,
  [CodigoTienda] [varchar](50) NULL,
  [RucEmisor] [varchar](50) NULL,
  [IdentificadorTerminal] [varchar](50) NULL,
  [NumeroTerminal] [float] NULL,
  [Serie] [varchar](50) NULL,
  [TipoTransaccion] [int] NULL,
  [NumeroTransaccion] [int] NULL,
  [Fecha] [datetime2] NULL,
  [Hora] [varchar](50) NULL,
  [Cajero] [varchar](50) NULL,
  [Vendedor] [varchar](50) NULL,
  [DNI] [varchar](50) NULL,
  [RUC] [varchar](50) NULL,
  [NombreCliente] [varchar](150) NULL,
  [DireccionCliente] [varchar](200) NULL,
  [Bonus] [varchar](50) NULL,
  [Moneda] [varchar](50) NULL,
  [MedioPago] [varchar](50) NULL,
  [TotalValorVentaBruta] [varchar](50) NULL,
  [DescuentosGlobal] [varchar](50) NULL,
  [MontoTotalIgv] [varchar](50) NULL,
  [TotalValorVentaNeta] [varchar](50) NULL,
  [OrdenItem] [varchar](50) NULL,
  [CantidadUnidadesItem] [varchar](50) NULL,
  [CodigoProducto] [varchar](50) NULL,
  [DescripcionProducto] [varchar](150) NULL,
  [PrecioVentaUnitarioItem] [varchar](50) NULL,
  [CargoDescuentoItem] [varchar](50) NULL,
  [PrecioTotalItem] [varchar](50) NULL
)
ON [PRIMARY]
GO